export const ACTIVATION_BEGIN = "ACTIVATION_BEGIN";
export const ACTIVATION_CLEAR = "ACTIVATION_CLEAR";
export const ACTIVATION_FAILURE = "ACTIVATION_FAILURE";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const REGISTRATION_BEGIN = "REGISTRATION_BEGIN";
export const REGISTRATION_CLEAR = "REGISTRATION_CLEAR";
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
